// 상품 상태
export const PRODUCT_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELED: 'CANCELED',
  PURCHASE_RESERVED: 'PURCHASE_RESERVED',
  SOLD: 'SOLD',
};

// 대여 상태
export const RENTAL_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELED: 'CANCELED',
  ON_RENTING: 'ON_RENTING',
};
